[font]
size = 14.0

[font.normal]
family = "TX-02-AREMU"

[font.offset]
y = 7

[window]
opacity = 0.85
decorations = "Buttonless"
blur = true
dynamic_padding = true

[window.padding]
x = 5
y = 0

[cursor.style]
shape = "Beam"
blinking = "On"

[scrolling]
multiplier = 2

[general]
import = ["~/.config/alacritty/colors.toml"]

[terminal.shell]
program = "zsh"
