
[ui]
zen = false
auto_center = true
view_mode = "single"
gutter_signs = true
topbar = true
stepping = false

[ui.blame]
enabled = true

[ui.diff]
fg = "theme"
bg = false
highlight = "none"
extent_marker = "diff"
extent_marker_scope = "hunk"
max_bytes = 2097152          # 2 MiB

[ui.theme]
name = "cyberdream"

[ui.syntax]
mode = "on"
theme = "cyberdream"

[ui.theme.defs]
bg = "none"
bgAlt = "none"
bgHighlight = "none"

[ui.theme.theme.backgroundPanel]
dark = "none"
light = "none"

[ui.evo]
syntax = "full"

[ui.split]
align_lines = true

[playback]
speed = 200
animation = true
animation_duration = 150
autoplay = false

[files]
panel_width = 30


# [ui]
# zen = false
# auto_center = true
# view_mode = "single"
# gutter_signs = false
# topbar = true
#
# [ui.blame]
# enabled = true
#
# [ui.diff]
# fg = "syntax"
# bg = true
# highlight = "text"
# extent_marker = "diff"
# extent_marker_scope = "hunk"
# max_bytes = 2097152          # 2 MiB
#
# [ui.theme]
# name = "cyberdream"
#
# [ui.syntax]
# mode = "on"
# theme = "cyberdream"
#
# [ui.theme.defs]
# bg = "none"
# bgAlt = "none"
# bgHighlight = "none"
#
# [ui.theme.theme.backgroundPanel]
# dark = "none"
# light = "none"
#
# [ui.evo]
# syntax = "full"
#
# [ui.split]
# align_lines = true
#
# [playback]
# speed = 200
# animation = true
# animation_duration = 150
# autoplay = false
#
# [files]
# panel_width = 30
